language: php

cache:
  directories:
    - $HOME/.composer/cache/files

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
  - php: 7.2
    env: WP_VERSION=latest WP_MULTISITE=1 COVERAGE=1
  - php: 7.2
    env: LINT=1

before_install:
  - |
    if [[ "$LINT" == "1" ]]; then
      export PHPCS_DIR=/tmp/phpcs
      export LINTS_DIR=/tmp/lint
      git clone -b master --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git $PHPCS_DIR
      git clone -b master --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git $LINTS_DIR
      $PHPCS_DIR/bin/phpcs --config-set installed_paths $LINTS_DIR
      phpenv rehash
    fi;

before_script:
  - if [[ "$COVERAGE" != "1" ]]; then phpenv config-rm xdebug.ini; fi
  - if find . -name "*.php" -exec php -l {} \; | grep "unexpected $end"; then exit 1; fi
  - composer install --prefer-dist --optimize-autoloader --no-scripts
  - bash tests/bin/install.sh gravitypdf_test root '' localhost $WP_VERSION

script:
 - |
   if [[ "$LINT" == "1" ]]; then
     $PHPCS_DIR/bin/phpcs -p .
   elif [[ "$COVERAGE" == "1" ]]; then
    ./vendor/bin/phpunit --coverage-clover=coverage/php-coverage1.xml
   else
    ./vendor/bin/phpunit
   fi

after_success:
 - if [[ "$COVERAGE" == "1" ]]; then bash <(curl -s https://codecov.io/bash); fi